# Generated by Django 4.2.9 on 2024-01-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='filePrefix',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
