# Generated by Django 4.2.9 on 2024-01-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_configuracion_fileprefix_configuracion_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giroscopio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='magnetometro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orientacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='presion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
